In [220]:
import os
import json
import csv

In [221]:
path1 = "E:/web_bot_detection_dataset/phase1/annotations/humans_and_advanced_bots/"
path2 = "E:/web_bot_detection_dataset/phase1/annotations/humans_and_moderate_bots/"

mm1= "E:/web_bot_detection_dataset/phase1/data/mouse_movements/humans_and_advanced_bots/"
mm2 = "E:/web_bot_detection_dataset/phase1/data/mouse_movements/humans_and_moderate_bots/"

In [222]:
mm1 = "E:/web_bot_detection_dataset/phase1/data/mouse_movements/humans_and_advanced_bots/"

output_csv = 'output_combined.csv'
with open(output_csv, 'w', newline='', encoding='utf-8') as csv_file:
    writer = csv.writer(csv_file)
    
    header_written = False  

    for subdir in os.listdir(mm1):
        subdir_path = os.path.join(mm1, subdir) 
        
        if os.path.isdir(subdir_path):
            for json_file_name in os.listdir(subdir_path):
                json_file_path = os.path.join(subdir_path, json_file_name)
                
                if json_file_name.endswith('.json'): 
                    with open(json_file_path, 'r', encoding='utf-8') as json_file:
                        data = json.load(json_file)
                        
                        if isinstance(data, dict):  
                            if not header_written:
                                header = data.keys()  
                                writer.writerow(header)
                                header_written = True
                            writer.writerow(data.values())  
                        
                        elif isinstance(data, list) and data and isinstance(data[0], dict):  
                            if not header_written:
                                header = data[0].keys()  
                                writer.writerow(header)
                                header_written = True
                            for row in data:
                                writer.writerow(row.values())  

print(f"CSV file has been created at {output_csv}.")

CSV file has been created at output_combined.csv.

In [237]:
data1 = pd.read_csv("output_combined.csv")
data1.head(2)

,session_id,total_behaviour,mousemove_times,mousemove_total_behaviour
0,071tbv7fsev5d64kb0f9jieor6,"[m(6,7)][m(14,15)][m(21,23)][m(29,31)][m(37,39...","624433306,624433314,624433330,624433347,624433...","[6,7][14,15][21,23][29,31][37,39][44,47][52,55..."
1,0i5kvpslrq3vb6u8ff2kuejv0v,"[m(7,6)][m(15,14)][m(23,22)][m(31,29)][m(39,37...","625982432,625982440,625982452,625982469,625982...","[7,6][15,14][23,22][31,29][39,37][47,45][55,52..."

In [224]:
mm2 = "E:/web_bot_detection_dataset/phase1/data/mouse_movements/humans_and_moderate_bots/"

output_csv = 'output_combined_moderate.csv'
with open(output_csv, 'w', newline='', encoding='utf-8') as csv_file:
    writer = csv.writer(csv_file)
    
    header_written = False  

    for subdir in os.listdir(mm2):
        subdir_path = os.path.join(mm2, subdir) 
        
        if os.path.isdir(subdir_path):
            for json_file_name in os.listdir(subdir_path):
                json_file_path = os.path.join(subdir_path, json_file_name)
                
                if json_file_name.endswith('.json'): 
                    with open(json_file_path, 'r', encoding='utf-8') as json_file:
                        data = json.load(json_file)
                        
                        if isinstance(data, dict): 
                            if not header_written:
                                header = data.keys()  
                                writer.writerow(header)
                                header_written = True
                            writer.writerow(data.values())  
                        
                        elif isinstance(data, list) and data and isinstance(data[0], dict):  
                            if not header_written:
                                header = data[0].keys()  
                                writer.writerow(header)
                                header_written = True
                            for row in data:
                                writer.writerow(row.values()) 

print(f"CSV file has been created at {output_csv}.")

CSV file has been created at output_combined_moderate.csv.

In [238]:
data2 = pd.read_csv("output_combined_moderate.csv")
data2.head()

,session_id,total_behaviour,mousemove_times,mousemove_total_behaviour
0,0ht0u328t4mkgi01sp7mm07e01,"[m(0,5)][m(0,6)][m(0,7)][m(0,8)][m(0,9)][m(1,1...","447717248,447717265,447717281,447717298,447717...","[0,5][0,6][0,7][0,8][0,9][1,10][1,11][1,12][1,..."
1,0oa2dua3mli7mrr32c0gd4o0i2,"[m(644,567)][m(644,566)][m(642,564)][m(641,562...","359242160,359242184,359242194,359242211,359242...","[644,567][644,566][642,564][641,562][638,557][..."
2,0ogg5l1i4nh37ek8mjpn8q9fc0,"[m(24,0)][m(24,1)][m(24,2)][m(24,3)][m(24,4)][...","443682927,443682939,443682955,443682972,443682...","[24,0][24,1][24,2][24,3][24,4][24,5][24,6][24,..."
3,0p0kaqfmftrtfg0u12rkshrdi9,"[m(544,545)][m(544,544)][m(543,543)][m(541,542...","215772898,215772921,215772936,215772953,215772...","[544,545][544,544][543,543][541,542][540,541][..."
4,0pcr6mashfodserb90cq3p04uf,"[m(0,0)][m(0,1)][m(0,2)][m(0,3)][m(0,4)][m(0,5...","444013245,444013261,444013278,444013295,444013...","[0,0][0,1][0,2][0,3][0,4][0,5][0,6][0,7][1,8][..."

In [239]:
data = pd.concat([data1,data2])

In [240]:
data.head()

,session_id,total_behaviour,mousemove_times,mousemove_total_behaviour
0,071tbv7fsev5d64kb0f9jieor6,"[m(6,7)][m(14,15)][m(21,23)][m(29,31)][m(37,39...","624433306,624433314,624433330,624433347,624433...","[6,7][14,15][21,23][29,31][37,39][44,47][52,55..."
1,0i5kvpslrq3vb6u8ff2kuejv0v,"[m(7,6)][m(15,14)][m(23,22)][m(31,29)][m(39,37...","625982432,625982440,625982452,625982469,625982...","[7,6][15,14][23,22][31,29][39,37][47,45][55,52..."
2,0oa2dua3mli7mrr32c0gd4o0i2,"[m(644,567)][m(644,566)][m(642,564)][m(641,562...","359242160,359242184,359242194,359242211,359242...","[644,567][644,566][642,564][641,562][638,557][..."
3,0p0kaqfmftrtfg0u12rkshrdi9,"[m(544,545)][m(544,544)][m(543,543)][m(541,542...","215772898,215772921,215772936,215772953,215772...","[544,545][544,544][543,543][541,542][540,541][..."
4,16r8lv9fabgjk06di8usnmu9ni,"[m(6,7)][m(14,15)][m(22,23)][m(30,31)][m(38,39...","613476016,613476024,613476037,613476053,613476...","[6,7][14,15][22,23][30,31][38,39][46,47][54,55..."

In [241]:
data.shape

(200, 4)

In [229]:
mm2 = "E:/web_bot_detection_dataset/phase1/data/mouse_movements/humans_and_moderate_bots/"
annotations_path = "E:/web_bot_detection_dataset/phase1/annotations/humans_and_moderate_bots/"

labels = {}

train_file_path = os.path.join(annotations_path, 'train')  

with open(train_file_path, 'r', encoding='utf-8') as train_file:
    for line in train_file:
        parts = line.strip().split()  
        if len(parts) >= 2:
            session_id = parts[0]  
            label = parts[1]      
            labels[session_id] = label  

output_csv = 'output_combined_moderate_with_labels.csv'

with open(output_csv, 'w', newline='', encoding='utf-8') as csv_file:
    writer = csv.writer(csv_file)
    
    header_written = False  

    for subdir in os.listdir(mm2):
        subdir_path = os.path.join(mm2, subdir)
        
        if os.path.isdir(subdir_path):
            for json_file_name in os.listdir(subdir_path):
                json_file_path = os.path.join(subdir_path, json_file_name)
                
                if json_file_name.endswith('.json'): 
                    with open(json_file_path, 'r', encoding='utf-8') as json_file:
                        data = json.load(json_file)
                        
                        session_id = data.get('session_id') 
                        label = labels.get(session_id, 'unknown')  
                        
                        if isinstance(data, dict):  
                            data['label'] = label 
                            if not header_written:
                                writer.writerow(data.keys())  
                                header_written = True
                            writer.writerow(data.values()) 
                        
                        elif isinstance(data, list) and data and isinstance(data[0], dict):  
                            for row in data:
                                row['label'] = label  
                                if not header_written:
                                    writer.writerow(row.keys())
                                    header_written = True
                                writer.writerow(row.values())

print(f"CSV file has been created at {output_csv}.")

CSV file has been created at output_combined_moderate_with_labels.csv.

In [230]:
label_data1 = pd.read_csv("output_combined_moderate_with_labels.csv")
label_data1.head()

,session_id,total_behaviour,mousemove_times,mousemove_total_behaviour,label
0,0ht0u328t4mkgi01sp7mm07e01,"[m(0,5)][m(0,6)][m(0,7)][m(0,8)][m(0,9)][m(1,1...","447717248,447717265,447717281,447717298,447717...","[0,5][0,6][0,7][0,8][0,9][1,10][1,11][1,12][1,...",moderate_bot
1,0oa2dua3mli7mrr32c0gd4o0i2,"[m(644,567)][m(644,566)][m(642,564)][m(641,562...","359242160,359242184,359242194,359242211,359242...","[644,567][644,566][642,564][641,562][638,557][...",human
2,0ogg5l1i4nh37ek8mjpn8q9fc0,"[m(24,0)][m(24,1)][m(24,2)][m(24,3)][m(24,4)][...","443682927,443682939,443682955,443682972,443682...","[24,0][24,1][24,2][24,3][24,4][24,5][24,6][24,...",moderate_bot
3,0p0kaqfmftrtfg0u12rkshrdi9,"[m(544,545)][m(544,544)][m(543,543)][m(541,542...","215772898,215772921,215772936,215772953,215772...","[544,545][544,544][543,543][541,542][540,541][...",human
4,0pcr6mashfodserb90cq3p04uf,"[m(0,0)][m(0,1)][m(0,2)][m(0,3)][m(0,4)][m(0,5...","444013245,444013261,444013278,444013295,444013...","[0,0][0,1][0,2][0,3][0,4][0,5][0,6][0,7][1,8][...",moderate_bot

In [231]:
mm1= "E:/web_bot_detection_dataset/phase1/data/mouse_movements/humans_and_advanced_bots/"
annotations_path = "E:/web_bot_detection_dataset/phase1/annotations/humans_and_advanced_bots/"


labels = {}

train_file_path = os.path.join(annotations_path, 'train')  

with open(train_file_path, 'r', encoding='utf-8') as train_file:
    for line in train_file:
        parts = line.strip().split()  
        if len(parts) >= 2:
            session_id = parts[0]  
            label = parts[1]       
            labels[session_id] = label  

output_csv = 'output_combined_advanced_with_labels.csv'

with open(output_csv, 'w', newline='', encoding='utf-8') as csv_file:
    writer = csv.writer(csv_file)
    
    header_written = False  

    for subdir in os.listdir(mm1):
        subdir_path = os.path.join(mm1, subdir)
        
        if os.path.isdir(subdir_path):
            for json_file_name in os.listdir(subdir_path):
                json_file_path = os.path.join(subdir_path, json_file_name)
                
                if json_file_name.endswith('.json'): 
                    with open(json_file_path, 'r', encoding='utf-8') as json_file:
                        data = json.load(json_file)
                        
                        session_id = data.get('session_id')  
                        label = labels.get(session_id, 'unknown')  
                        
                        if isinstance(data, dict):  
                            data['label'] = label  
                            if not header_written:
                                writer.writerow(data.keys())  
                                header_written = True
                            writer.writerow(data.values())  
                        
                        elif isinstance(data, list) and data and isinstance(data[0], dict):  
                            for row in data:
                                row['label'] = label  
                                if not header_written:
                                    writer.writerow(row.keys())  
                                    header_written = True
                                writer.writerow(row.values()) 

print(f"CSV file has been created at {output_csv}.")

CSV file has been created at output_combined_advanced_with_labels.csv.

In [232]:
label_data2 = pd.read_csv("output_combined_advanced_with_labels.csv")
label_data2.head(3)

,session_id,total_behaviour,mousemove_times,mousemove_total_behaviour,label
0,071tbv7fsev5d64kb0f9jieor6,"[m(6,7)][m(14,15)][m(21,23)][m(29,31)][m(37,39...","624433306,624433314,624433330,624433347,624433...","[6,7][14,15][21,23][29,31][37,39][44,47][52,55...",advanced_bot
1,0i5kvpslrq3vb6u8ff2kuejv0v,"[m(7,6)][m(15,14)][m(23,22)][m(31,29)][m(39,37...","625982432,625982440,625982452,625982469,625982...","[7,6][15,14][23,22][31,29][39,37][47,45][55,52...",advanced_bot
2,0oa2dua3mli7mrr32c0gd4o0i2,"[m(644,567)][m(644,566)][m(642,564)][m(641,562...","359242160,359242184,359242194,359242211,359242...","[644,567][644,566][642,564][641,562][638,557][...",human

In [236]:
final_df = pd.concat([label_data1,label_data2])
final_df.sample(10)

,session_id,total_behaviour,mousemove_times,mousemove_total_behaviour,label
74,qe370ks533bvqh8n9ra33968bn,"[m(0,0)][m(0,1)][m(0,2)][m(0,3)][m(0,4)][m(0,5...","441474168,441474177,441474187,441474206,441474...","[0,0][0,1][0,2][0,3][0,4][0,5][0,6][0,7][0,8][...",moderate_bot
95,v3hbnujku5f0bm2mmbjqrr9rg8,"[m(7,6)][m(15,14)][m(23,22)][m(31,30)][m(39,38...","621539491,621539502,621539518,621539535,621539...","[7,6][15,14][23,22][31,30][39,38][47,46][55,53...",advanced_bot
99,vtcjrbtjq57mnai4banl61pd25,"[m(7,6)][m(15,14)][m(23,22)][m(31,30)][m(39,37...","623792363,623792373,623792389,623792412,623792...","[7,6][15,14][23,22][31,30][39,37][47,45][55,53...",advanced_bot
79,rfvugmk87jtlaiilouut5sdm32,"[m(590,562)][m(592,559)][m(595,557)][m(597,554...","300678746,300678757,300678773,300678790,300678...","[590,562][592,559][595,557][597,554][598,551][...",human
89,t8f9bu34vogoj5kisdk61hp83n,"[m(0,5)][m(0,6)][m(0,7)][m(0,8)][m(0,9)][m(0,1...","440377967,440377983,440378000,440378017,440378...","[0,5][0,6][0,7][0,8][0,9][0,10][1,11][1,12][1,...",moderate_bot
71,p9rb949jj3aci28mne75opl41i,"[m(276,439)][m(273,436)][m(272,435)][m(272,434...","206293735,206293769,206293784,206293800,206293...","[276,439][273,436][272,435][272,434][271,433][...",human
81,s74076j0vtua7ct0fkej7ehmt8,"[m(653,1)][m(660,14)][m(667,29)][m(684,73)][m(...","202578080,202578086,202578100,202578118,202578...","[653,1][660,14][667,29][684,73][686,84][688,11...",human
65,k5pg7u2907cb9nk61dd8i15fm2,"[m(425,492)][m(415,485)][m(410,482)][m(398,473...","204596069,204596085,204596102,204596119,204596...","[425,492][415,485][410,482][398,473][389,465][...",human
2,0ogg5l1i4nh37ek8mjpn8q9fc0,"[m(24,0)][m(24,1)][m(24,2)][m(24,3)][m(24,4)][...","443682927,443682939,443682955,443682972,443682...","[24,0][24,1][24,2][24,3][24,4][24,5][24,6][24,...",moderate_bot
48,gh9s7753br49h4c8g669fucshp,"[m(585,560)][m(584,560)][m(583,560)][m(583,561...","216360862,216361022,216361052,216361060,216361...","[585,560][584,560][583,560][583,561][582,561][...",human

In [246]:
final_df.to_csv("web_bot_detection.csv")

In [258]:
final_df = final_df.reset_index(drop="index")

In [259]:
import numpy as np
import pandas as pd

def extract_time_intervals(times):
    try:
        if pd.isna(times) or not isinstance(times, str):
            return np.array([]) 

        times_list = [int(t.strip()) for t in times.split(",") if t.strip().isdigit()]
        
        if len(times_list) < 2:
            return np.array([]) 

        return np.diff(times_list)  
    except Exception as e:
        print(f"Error processing: {times} - {e}")
        return np.array([])

final_df["time_intervals"] = final_df["mousemove_times"].apply(extract_time_intervals)

In [260]:
final_df.head()

,session_id,total_behaviour,mousemove_times,mousemove_total_behaviour,label,time_intervals
0,0ht0u328t4mkgi01sp7mm07e01,"[m(0,5)][m(0,6)][m(0,7)][m(0,8)][m(0,9)][m(1,1...","447717248,447717265,447717281,447717298,447717...","[0,5][0,6][0,7][0,8][0,9][1,10][1,11][1,12][1,...",moderate_bot,"[17, 16, 17, 17, 16, 17, 17, 16, 17, 24, 17, 1..."
1,0oa2dua3mli7mrr32c0gd4o0i2,"[m(644,567)][m(644,566)][m(642,564)][m(641,562...","359242160,359242184,359242194,359242211,359242...","[644,567][644,566][642,564][641,562][638,557][...",human,"[24, 10, 17, 16, 18, 16, 17, 18, 16, 17, 16, 1..."
2,0ogg5l1i4nh37ek8mjpn8q9fc0,"[m(24,0)][m(24,1)][m(24,2)][m(24,3)][m(24,4)][...","443682927,443682939,443682955,443682972,443682...","[24,0][24,1][24,2][24,3][24,4][24,5][24,6][24,...",moderate_bot,"[12, 16, 17, 17, 16, 17, 17, 16, 17, 17, 16, 1..."
3,0p0kaqfmftrtfg0u12rkshrdi9,"[m(544,545)][m(544,544)][m(543,543)][m(541,542...","215772898,215772921,215772936,215772953,215772...","[544,545][544,544][543,543][541,542][540,541][...",human,"[23, 15, 17, 12, 17, 20, 20, 10, 14, 17, 28, 6..."
4,0pcr6mashfodserb90cq3p04uf,"[m(0,0)][m(0,1)][m(0,2)][m(0,3)][m(0,4)][m(0,5...","444013245,444013261,444013278,444013295,444013...","[0,0][0,1][0,2][0,3][0,4][0,5][0,6][0,7][1,8][...",moderate_bot,"[16, 17, 17, 9, 17, 16, 17, 17, 16, 18, 16, 17..."

- total_behaviour: 

   The mouse movement actions of the visitor. These actions can be either move, right click, left click or middle click. The move is written as m(x,y), where the x and y indicate the coordinates of the mouse move. The right, left and middle click are written as c(l), c(r), and c(m) respectively
--------------------------------------------------------------------------------------------------------------------

- mousemove_times:

    the timestamp of when each mouse move was performed in the form of {(t0), (t1), …, (tn)}, where n is the total number of points over which the mouse hovered in each web page.



--------------------------------------------------------------------------------------------------------------------

- mousemove_total_behaviour: 


    the coordinates of the current mouse point in the form of {(x0, y0), (x1, y1), …, (xn, yn)}, where n is the total number of points over which the mouse hovered in each web page.